import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAuditLogFields1767881469787 implements MigrationInterface {
    name = 'AddAuditLogFields1767881469787'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP CONSTRAINT "property_dependencies_source_property_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP CONSTRAINT "property_dependencies_target_property_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP CONSTRAINT "product_properties_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP CONSTRAINT "product_properties_property_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP CONSTRAINT "price_modifiers_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP CONSTRAINT "price_modifiers_property_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_entity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_timestamp"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_role_check"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "properties_type_check"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_unit_check"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP CONSTRAINT "price_modifiers_change_type_check"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_action_check"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP CONSTRAINT "product_properties_product_id_property_id_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "person_type"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "possible_values"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "source_property_id"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "source_value"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "target_property_id"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "target_value"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "default_length"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "default_width"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "default_depth"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "base_price"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "product_id"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "property_id"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "default_value"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "product_id"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "property_id"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "property_value"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "price_change"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "change_type"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "section_type"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "order_templates" DROP CONSTRAINT "order_templates_order_type_key"`);
        await queryRunner.query(`ALTER TABLE "order_templates" DROP COLUMN "order_type"`);
        await queryRunner.query(`ALTER TABLE "order_templates" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "order_templates" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "timestamp"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "old_value"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "new_value"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "code" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "UQ_220d2c2f64cf6d6eeb6816b84a8" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "dataType" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "possibleValues" text`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "defaultValue" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "isRequired" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "displayOrder" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "sourcePropertyId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "targetPropertyId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "dependencyType" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "sourceValue" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "targetValue" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" ADD "code" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "UQ_7cfc24d6c24f0ec91294003d6b8" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "products" ADD "basePrice" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "products" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "productId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "propertyId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "isRequired" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "displayOrder" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "code" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD CONSTRAINT "UQ_3836d34c7137695cccb261287ad" UNIQUE ("code")`);
        await queryRunner.query(`CREATE TYPE "public"."price_modifiers_modifiertype_enum" AS ENUM('fixed_price', 'percentage', 'fixed_amount', 'per_unit', 'multiplier')`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "modifierType" "public"."price_modifiers_modifiertype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "value" numeric(15,4) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "propertyId" integer`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "propertyValue" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "priority" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "templateId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "sectionNumber" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "defaultName" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "isRequired" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_templates" ADD "code" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_templates" ADD CONSTRAINT "UQ_9880e9dbe9f1b9f4ae78ece9371" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "order_templates" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "order_templates" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order_templates" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "username" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "changes" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ip_address" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "full_name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "category" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_id" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_0395030e640f89091b97f14c4b" ON "properties" ("isActive") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_220d2c2f64cf6d6eeb6816b84a" ON "properties" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd8f97adc1445d8f53f996e354" ON "property_dependencies" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_fcca19259b37897f053aa3b273" ON "property_dependencies" ("targetPropertyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8de74cd15430047e207990f5a1" ON "property_dependencies" ("sourcePropertyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff39b9ac40872b2de41751eedc" ON "products" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3932231d2385ac248d0888d95" ON "products" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7cfc24d6c24f0ec91294003d6b" ON "products" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_95259293562e208736d711b9f6" ON "product_properties" ("productId", "propertyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0e3aa4fb6cdbc4873474e6db3" ON "product_properties" ("propertyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cffc9e18f85a8d8173e5d835ee" ON "product_properties" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a87359ac30f88f43ceab9dc33" ON "price_modifiers" ("propertyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_242a431c22c07d92dc81f389a1" ON "price_modifiers" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_3836d34c7137695cccb261287a" ON "price_modifiers" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_20899ea8f5c25f7758e46b4802" ON "order_section_templates" ("templateId", "sectionNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_dad0b41f0b64cb6c05ab21b828" ON "order_section_templates" ("templateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6273f4275b521798f3000ced87" ON "order_templates" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_9880e9dbe9f1b9f4ae78ece937" ON "order_templates" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea9ba3dfb39050f831ee3be40d" ON "audit_logs" ("entity_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD CONSTRAINT "FK_dad0b41f0b64cb6c05ab21b8281" FOREIGN KEY ("templateId") REFERENCES "order_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP CONSTRAINT "FK_dad0b41f0b64cb6c05ab21b8281"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea9ba3dfb39050f831ee3be40d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9880e9dbe9f1b9f4ae78ece937"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6273f4275b521798f3000ced87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dad0b41f0b64cb6c05ab21b828"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20899ea8f5c25f7758e46b4802"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3836d34c7137695cccb261287a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_242a431c22c07d92dc81f389a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a87359ac30f88f43ceab9dc33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cffc9e18f85a8d8173e5d835ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0e3aa4fb6cdbc4873474e6db3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95259293562e208736d711b9f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cfc24d6c24f0ec91294003d6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3932231d2385ac248d0888d95"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff39b9ac40872b2de41751eedc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8de74cd15430047e207990f5a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcca19259b37897f053aa3b273"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd8f97adc1445d8f53f996e354"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_220d2c2f64cf6d6eeb6816b84a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0395030e640f89091b97f14c4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entity_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entity_id" integer`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "category" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "full_name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "changes"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "order_templates" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "order_templates" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "order_templates" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "order_templates" DROP CONSTRAINT "UQ_9880e9dbe9f1b9f4ae78ece9371"`);
        await queryRunner.query(`ALTER TABLE "order_templates" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "isRequired"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "defaultName"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "sectionNumber"`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" DROP COLUMN "templateId"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "priority"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "propertyValue"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "propertyId"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "modifierType"`);
        await queryRunner.query(`DROP TYPE "public"."price_modifiers_modifiertype_enum"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP CONSTRAINT "UQ_3836d34c7137695cccb261287ad"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "displayOrder"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "isRequired"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "propertyId"`);
        await queryRunner.query(`ALTER TABLE "product_properties" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "basePrice"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "UQ_7cfc24d6c24f0ec91294003d6b8"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "targetValue"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "sourceValue"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "dependencyType"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "targetPropertyId"`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" DROP COLUMN "sourcePropertyId"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "displayOrder"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "isRequired"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "defaultValue"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "possibleValues"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "dataType"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "UQ_220d2c2f64cf6d6eeb6816b84a8"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_deleted"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "new_value" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "old_value" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "timestamp" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "order_templates" ADD "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "order_templates" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "order_templates" ADD "order_type" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_templates" ADD CONSTRAINT "order_templates_order_type_key" UNIQUE ("order_type")`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_section_templates" ADD "section_type" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "change_type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "price_change" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "property_value" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "property_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD "product_id" integer`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "default_value" text`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "property_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD "product_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "products" ADD "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "products" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "products" ADD "base_price" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "products" ADD "default_depth" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "default_width" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "default_length" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "target_value" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "target_property_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "source_value" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD "source_property_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "possible_values" text array`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "category" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "person_type" character varying(50) array`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD CONSTRAINT "product_properties_product_id_property_id_key" UNIQUE ("product_id", "property_id")`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_action_check" CHECK (((action)::text = ANY ((ARRAY['create'::character varying, 'update'::character varying, 'delete'::character varying, 'status_change'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD CONSTRAINT "price_modifiers_change_type_check" CHECK (((change_type)::text = ANY ((ARRAY['absolute'::character varying, 'percentage'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_unit_check" CHECK (((unit)::text = ANY ((ARRAY['m2'::character varying, 'linear_meter'::character varying, 'piece'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "properties_type_check" CHECK (((type)::text = ANY ((ARRAY['string'::character varying, 'number'::character varying, 'boolean'::character varying, 'enum'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_role_check" CHECK (((role)::text = ANY ((ARRAY['client'::character varying, 'manager'::character varying, 'worker'::character varying, 'admin'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_timestamp" ON "audit_logs" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_entity" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_is_active" ON "users" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role" ON "users" ("role") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD CONSTRAINT "price_modifiers_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_modifiers" ADD CONSTRAINT "price_modifiers_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD CONSTRAINT "product_properties_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_properties" ADD CONSTRAINT "product_properties_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD CONSTRAINT "property_dependencies_target_property_id_fkey" FOREIGN KEY ("target_property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_dependencies" ADD CONSTRAINT "property_dependencies_source_property_id_fkey" FOREIGN KEY ("source_property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
